### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by ben-manes** [ayedo/jooq-modelator#6]
The versions required by this plugin are not forward compatible with later releases, e.g.

```
Caused by: java.lang.NoClassDefFoundError: org/flywaydb/core/internal/util/jdbc/DriverDataSource
  at ch.ayedo.jooqmodelator.core.FlywayDependentHealthChecker.<init>(HealthCheck.kt:28)
```

**Comment by ben-manes** [comment]
This impacts working with Postgres 11 or later, as Flyway clean doesn't work with the current version.

**Comment by ayedo** [comment]
I have bumped the versions. I'm not too comfortable depending on a 'beta' version of Flyway, but Postgres 11 support is important. I hope the Flyway guys release the final 6 version soon.

**Comment by ben-manes** [comment]
Oh sorry, I’m on the latest 5.x which was not backwards compatible but does work with 11 fine. I agree using the beta is uncomfortable. I’ll try again in a few hours when at work. Thank you!

**Comment by ben-manes** [comment]
It looks like `5.2.4` doesn't handle `clean` properly on Postgres 10+, whereas the 6-beta does. Obviously I'm not running clean on production, so I never noticed 😄.

I am currently using H2 with custom mappings to override, which isn't great for tests and doubling the scripts. Moving to this plugin or similar has been on my backlog, and looks like I should wait until 6.0 before transitioning. Thanks for doing the hard part of putting this all together! 😅

**Comment by ayedo** [comment]
Well, I did bump the version to the beta on the newest release of the plugin. The tests passed, also for Postgres 11. I feel like there might be a miss-understanding.

**Comment by ben-manes** [comment]
Yes, the test would pass with Postgres 11. I use jsonb which has some special characters for its operations, such as
```sql
AND (data->'business'->'addresses'->0->'label')::jsonb ? 'Mailing Address';
```
Flyway parses the SQL itself and `?` is not a valid character in the latest beta. They fixed this last week it seems. If I comment out those SQL statements then this plugin works perfectly. If I force a downgrade to `5.2.4` which doesn't have this parsing bug, it fails because that version of Flyway lacks Postgres 11 support for `clean`. This isn't a problem with your plugin, but a blocker for me to move forward until Flyway's next release.
