### ISSUE TITLE
jooqOutputPath property is ignored

### ISSUE THREAD

**Issue by robfletcher** [ayedo/jooq-modelator#8]
No matter what I set `jooqOutputPath` the generated code ends up in the directory specified in `jooqConfig.xml` or in the default `target/generated-sources`.

**Comment by ayedo** [comment]
Hi Rob! Yes, I see now how this is confusing. The jOOQ generator is configured with the jooqConfig.xml, not in the plugin configuration. The reason the jooqOutputPath is required to be configured again (and kept in sync with the jooqConfix.xml) in the plugin configuration is for the incremental build support. It would be nice if the plugin could read this information from the jooqConfig.xml. I will see if I can add this feature in the future.

**Comment by ayedo** [comment]
I just saw that this information was missing from the documentation. I'm sorry. I've added it. Hopefully I'll find time soon to look into this soon.

**Comment by robfletcher** [comment]
I see, thanks. I didn't realize anything was being done with incremental compilation, that's useful to know.

**Comment by ayedo** [comment]
Yes, the plugin uses Gradles incremental compilation features, and only runs migrations if the output folder, or any the migrations folders have changed. Closing now.
